### ISSUE TITLE
Cursor location after insert and quit

### ISSUE THREAD

**Issue by stokhos** [kneasle/sapling#49] opened 2020-12-16 21:16 UTC
I noticed that after insert in DAG, the cursor stays at where it was.  It would be be convenient to move the cursor to the new added node.

After quitting, the DAG still exists, until it goes out of the scope. Is this an expected behaviour?

**Comment by kneasle** [comment] 2020-12-18 11:46
> I noticed that after insert in DAG, the cursor stays at where it was. It would be be convenient to move the cursor to the new added node.

Good point - I think this was the behaviour mostly because I forgot to implement anything else.  I'll go through the cases individually...

### Inserting siblings (`i*` and `a*`)

For `i*` and `a*`, I 100% agree - this should be the default behaviour (in fact, it _is_ already the default for `i*`).

Do you want to fix `a*`? - I can make a `good-first-issue` for it or if you want to do it you can simply make a PR.  The current infrastructure for edits leaves some things to be desired about how easy it is to break things by moving the cursor at the wrong time (you have to move the cursor **after** the call to `finish_edit`, which is really counter-intuitive).

### Inserting siblings (`o*`)

However, for `o*` there's the added complication of what the behaviour of adding a count should be.

For example, suppose I have simply an empty JSON array (`[]`), which I'm selecting.  Intuitively, I think I would expect `3ot` to insert `true` three times into the array resulting in `[true, true, true]`.  I'm not sure where the cursor should end up - I think either no movement or moving to the last thing you inserted would both be logical.

If the cursor doesn't move when `o*` is run, then the expected behaviour of `3ot` is trivial since `3ot` should be the same as `ototot` and inserting true 3 times manually will insert it as children of the cursor as expected.

If the cursor *does* move when `o*` is run, then the expected behaviour of `3ot` is **not** what happens if you type `ototot`, since the first `ot` would move the cursor to the newly created `true` and all further insertions would fail.

However, moving the cursor differently in the case of counts is definitely not without precedent: in Vim, typing `3rX` on `[H]ello World` (where `[*]` donates the cursor location) results in `XX[X]lo World` (the cursor has been moved forwards so that 3 different chars got replaced) - whereas typing `rXrXrX` would result in `[X]ello World` (the same character getting replaced three times because the cusor didn't move).

I think that in general we should try to avoid counts having different behaviours wherever possible, but in this case I think it's probably worth making an exception as not doing so is probably less intuitive.  @Kixunil, what do you reckon?

---

> After quitting, the DAG still exists, until it goes out of the scope. Is this an expected behaviour?

I think so?  In Rust every variable exists until it goes out of scope so I'm not sure I understand the question (I may just be being silly, though).  At any rate, once the DAG has returned from its mainloop no further edits are possible so the DAG won't be modified.

**Comment by Kixunil** [comment] 2020-12-18 18:42
Hmm, interesting. I guess making `3ot` adding three times `true` to an array without adding any other feature would be mosrt practical. However, I could imagine someone wanting to create 3-deep array/object, so having a separate feature for it would make sense. One way to do it is to allow both `3ot` and `o3t` and let them behave differently  (`3dl` and `d3l` are both accepted in vim and behave the same, I think this kind of divergence is reasonable). Not entirely sure which should be which but `3oa` making 3-deep array and `o3a` appending 3 arrays feels more intuitive. We would have to prohibit numbers to identify node types but that doesn't sound like  bad thing.

You bring a good point about `r` and I think that this kind of inconsistency results in a more practical outcome. While I like consistency in general, it may not be the most important thing in the world. So `3ot` inserting 3 times true and then moving cursor at the last inserted `true` would still make sense to me.

**Comment by stokhos** [comment] 2020-12-18 20:26
I can to fix this.

**Comment by kneasle** [comment] 2020-12-19 17:04
### @Kixunil 

> Hmm, interesting. I guess making `3ot` adding three times `true` to an array without adding any other feature would be mosrt practical. However, I could imagine someone wanting to create 3-deep array/object, so having a separate feature for it would make sense. One way to do it is to allow both `3ot` and `o3t` and let them behave differently (`3dl` and `d3l` are both accepted in vim and behave the same, I think this kind of divergence is reasonable). Not entirely sure which should be which but `3oa` making 3-deep array and `o3a` appending 3 arrays feels more intuitive.

I really like this - it fits very nicely with how English works: `o3t` = `o(3t)` should 'insert three `true`s' whereas `3oa` = `3(oa)` should '(insert an array) three times'.

> We would have to prohibit numbers to identify node types but that doesn't sound like bad thing.

I think this would be useful to avoid confusion anyway - I think it would be nice to have things like `+` and `*` as node-type identifiers for standard expressions, but I think banning numbers is probably fine.

---

### @stokhos 

> No need to make it `good-first-issue`, I can fix this.

Coooool!

> I thought DAG should be invalid after quitting, but this seems trivial.

I think that the real issue is that `Quit` is an `Action`, and therefore has to be passed through `DAG`.  But `DAG` should not decide when Sapling should quit because that quitting requires `return`ing from the mainloop of `Editor` (which is not `DAG`'s responsibility).  I have a plan to do some bigger refactoring that will hopefully resolve this.

**Comment by stokhos** [comment] 2020-12-22 09:13
I have fixed `a*`.

**Comment by kneasle** [comment] 2020-12-22 22:43
Are you sure you've fixed `a*` in #56? I've tested it in `master`, and got the old behaviour.

Also, in #53 I've completely refactored how the code for `DAG` works, which will make your change really hard to merge in.  So you'll have to redo it - this is just one of those things with working on projects with small code and lots of big changes.

**Comment by stokhos** [comment] 2020-12-23 06:36
> Are you sure you've fixed `a*` in #56? I've tested it in `master`, and got the old behaviour.
> 
> Also, in #53 I've completely refactored how the code for `DAG` works, which will make your change really hard to merge in. So you'll have to redo it - this is just one of those things with working on projects with small code and lots of big changes.

I guess I made a mistake when using git. 
I will redo it .

**Comment by kneasle** [comment] 2020-12-23 10:52
> I guess I made a mistake when using git.

This is very easily done - git is an amazing piece of software, but is objectively hard to learn. I recently found [this article](https://github.blog/2020-12-17-commits-are-snapshots-not-diffs/) from Github which does a nice job of clearing up some of the more confusing bits of Git. 

> I will redo it.

Cool - none of the edit code for `a*` has actually changed very much - the only real difference is that moving the cursor during an edit doesn't cause everything to break.

**Closed** 2020-12-26 23:43 UTC
Labels: bug
